version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    main: .
    binary: runx
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

brews:
  - name: runx
    homepage: https://github.com/ChengaDev/runx
    description: Run any saved project from anywhere on your system.
    license: MIT
    repository:
      owner: ChengaDev
      name: homebrew-tap
      branch: main
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    directory: .
    install: |
      bin.install "runx"
    test: |
      system "#{bin}/runx", "--help"
